apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftpwarden.name" . }}-config
  namespace: {{ include "sftpwarden.namespace" . }}
  labels:
    {{- include "sftpwarden.labels" . | nindent 4 }}
data:
  sftpwarden.yaml: |
    {{- .Values.sftpwardenConfig | nindent 4 }}
