apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftpwarden.name" . }}-config
  namespace: {{ include "sftpwarden.namespace" . }}
  labels:
    {{- include "sftpwarden.labels" . | nindent 4 }}
data:
  sftpwarden.yaml: |
    {{- .Values.sftpwardenConfig | nindent 4 }}
{{- $providerTextType := or (eq .Values.provider.type "yaml") (eq .Values.provider.type "csv") -}}
{{- if and .Values.persistence.provider.enabled .Values.provider.bootstrapContent $providerTextType }}
  {{ base .Values.provider.path }}: |
    {{- .Values.provider.bootstrapContent | nindent 4 }}
{{- end }}
