apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hostKeys.secretName }}
  namespace: {{ include "sftpwarden.namespace" . }}
  labels:
    {{- include "sftpwarden.labels" . | nindent 4 }}
type: Opaque
stringData: {}
{{- if and .Values.provider.dsnSecretName .Values.provider.createDsnSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.provider.dsnSecretName }}
  namespace: {{ include "sftpwarden.namespace" . }}
  labels:
    {{- include "sftpwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.provider.dsnSecretKey }}: {{ .Values.provider.dsnSecretValue | quote }}
{{- end }}
