services:
  sftpwarden-watcher:
    image: sftpwarden-watcher:local
    build:
      context: ../..
      dockerfile: docker/watcher/Dockerfile
    volumes:
      - ~/.sftpwarden:/root/.sftpwarden:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ~/.ssh/sftpwarden_deploy:/root/.ssh/sftpwarden_deploy:ro
