apiVersion: v1
kind: Secret
metadata:
  name: sftpwarden-host-keys
  namespace: sftpwarden
type: Opaque
stringData:
  ssh_host_ed25519_key: "REPLACE_WITH_PRIVATE_HOST_KEY"
  ssh_host_ed25519_key.pub: "REPLACE_WITH_PUBLIC_HOST_KEY"
  ssh_host_rsa_key: "REPLACE_WITH_PRIVATE_HOST_KEY"
  ssh_host_rsa_key.pub: "REPLACE_WITH_PUBLIC_HOST_KEY"
